/* Fauxbulous creator visuals v20 - stable mobile layout */
(()=>{'use strict';
const $=(q,r=document)=>r.querySelector(q);
const HIDE_KEY='faux-hide-cheeky-welcome-v1';
const WELCOME_KEY='faux-cheeky-welcome-seen-v1';
const css=`
.creatorCard{display:grid;grid-template-columns:92px 1fr;gap:14px;align-items:center;overflow:hidden}.creatorPhoto{width:92px;height:92px;border-radius:22px;object-fit:cover;object-position:center 30%;border:1px solid #ffffff2b;box-shadow:0 0 28px #ff4fcf26;background:#120717}.creatorKicker{font-size:9px;letter-spacing:1.6px;color:#ffffff88;font-weight:900}.creatorName{font-size:18px;font-weight:1000;margin:3px 0}.creatorSub{font-size:11px;line-height:1.45;color:#ffffffa8}
.founderInline{margin:12px 0 0;border:1px solid #ffffff20;border-radius:20px;overflow:hidden;background:#09040d;box-shadow:0 14px 35px #0008}.founderInline img{display:block;width:100%;height:auto;max-height:260px;object-fit:cover;object-position:center 48%}.founderInlineMeta{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:8px 10px;font-size:9px;color:#ffffff88}.founderInlineMeta b{color:#fff;letter-spacing:.7px;font-size:9px}.actionCard{margin-top:12px!important;padding-top:15px!important;overflow:hidden!important}.fauxFounderFrame,.fauxFounderCaption{display:none!important}
.cheekyBox{font-size:14px;line-height:1.55;text-align:center;padding:4px 4px 12px}.cheekyCheck{display:flex;align-items:center;justify-content:center;gap:8px;font-size:11px;color:#ffffffa5;margin:10px 0 2px}.cheekyCheck input{width:18px;height:18px;accent-color:#ff53c9}
@media(max-width:560px){.creatorCard{grid-template-columns:78px 1fr}.creatorPhoto{width:78px;height:78px;border-radius:19px}.creatorName{font-size:16px}.founderInline img{max-height:210px}}
`;
const st=document.createElement('style');st.id='creatorV20Style';st.textContent=css;document.head.appendChild(st);
function cleanOldFounder(){document.querySelectorAll('#fauxFounderFrame,.fauxFounderFrame,.fauxFounderCaption').forEach(x=>x.remove())}
function addCreatorCard(){const content=$('#content');if(!content)return;let card=$('#creatorCard');if(!card){card=document.createElement('section');card.id='creatorCard';card.className='card creatorCard';const dock=$('#modeDock'),hero=$('.hero');(dock||hero)?.after(card)}card.className='card creatorCard';card.innerHTML=`<img class="creatorPhoto" src="./assets/rebecca-creator.jpg?v=20" alt=""><div><div class="creatorKicker">THE HUMAN BEHIND THE FAUX</div><div class="creatorName">Brought to you by Rebecca Lynn / Fauxbulous</div><div class="creatorSub">Built for people who want better AI image prompts without needing a photography degree, a film crew, or seventeen browser tabs.</div></div>`}
function addFounderInline(){cleanOldFounder();const action=$('.actionCard');if(!action)return;let wrap=$('#founderInline');if(!wrap){wrap=document.createElement('div');wrap.id='founderInline';wrap.className='founderInline';action.prepend(wrap)}wrap.innerHTML=`<img src="./assets/rebecca-recline.jpg?v=20" alt=""><div class="founderInlineMeta"><span>Built by Rebecca Lynn</span><b>REBECCA LYNN · FAUXBULOUS</b></div>`}
function addWelcome(){if($('#cheekyWelcome'))return $('#cheekyWelcome');const d=document.createElement('div');d.id='cheekyWelcome';d.className='modal hidden';d.setAttribute('role','dialog');d.setAttribute('aria-modal','true');d.innerHTML=`<div class="modalGlass"><div class="modalTitle center">WELCOME TO FAUXBULOUS ✨</div><div class="cheekyBox">You made it in. Pick a vibe, make questionable creative decisions, and blame the AI if somebody grows a surprise finger. Rebecca has standards. The machines are still learning them. 😏</div><label class="cheekyCheck"><input id="hideCheeky" type="checkbox"> Don’t show this every time</label><button id="cheekyEnter" class="confirmBtn" type="button">LET ME CREATE</button></div>`;document.body.appendChild(d);$('#cheekyEnter').onclick=()=>{if($('#hideCheeky').checked)localStorage.setItem(HIDE_KEY,'1');localStorage.setItem(WELCOME_KEY,'1');d.classList.add('hidden')};return d}
function maybeWelcome(){const d=addWelcome();if(localStorage.getItem(HIDE_KEY)==='1')return;const access=$('#accessModal');const unlocked=!access||access.classList.contains('hidden');if(unlocked&&!localStorage.getItem(WELCOME_KEY))setTimeout(()=>d.classList.remove('hidden'),350)}
function boot(){cleanOldFounder();addCreatorCard();addFounderInline();addWelcome()}
window.addEventListener('DOMContentLoaded',()=>{boot();setTimeout(boot,350);setTimeout(maybeWelcome,600);const accessBtn=$('#accessEnter');if(accessBtn)accessBtn.addEventListener('click',()=>setTimeout(maybeWelcome,550))});
})();