/* Fauxbulous creator card + welcome v8 */
(()=>{'use strict';
const $=(q,r=document)=>r.querySelector(q);
const HIDE_KEY='faux-hide-cheeky-welcome-v1';
const WELCOME_KEY='faux-cheeky-welcome-seen-v1';
const css=`.creatorCard{display:grid;grid-template-columns:82px 1fr;gap:13px;align-items:center;overflow:hidden;position:relative}.creatorCard:before{content:'';position:absolute;inset:-40% auto auto 50%;width:180px;height:180px;border-radius:50%;background:radial-gradient(circle,#ff55cc33,transparent 68%);pointer-events:none}.creatorPhoto{width:82px;height:82px;border-radius:22px;object-fit:cover;border:1px solid #ffffff2b;box-shadow:0 0 28px #ff4fcf26}.creatorKicker{font-size:9px;letter-spacing:1.6px;color:#ffffff88;font-weight:900}.creatorName{font-size:18px;font-weight:1000;margin:3px 0}.creatorSub{font-size:11px;line-height:1.45;color:#ffffffa8}.cheekyBox{font-size:14px;line-height:1.55;text-align:center;padding:4px 4px 12px}.cheekyCheck{display:flex;align-items:center;justify-content:center;gap:8px;font-size:11px;color:#ffffffa5;margin:10px 0 2px}.cheekyCheck input{width:18px;height:18px;accent-color:#ff53c9}.actionCard{position:relative;overflow:visible;margin-top:118px;padding-top:18px}.fauxFounderFrame{position:absolute;left:-4px;right:-4px;bottom:68%;height:170px;pointer-events:none;z-index:0;overflow:visible}.fauxFounderGlow{position:absolute;left:2%;right:2%;bottom:0;height:70%;background:radial-gradient(ellipse at center,#a35cff38 0,#ff4fcf1f 35%,transparent 72%);filter:blur(10px)}.fauxFounderImage{position:absolute;left:50%;bottom:-8px;transform:translateX(-50%);width:min(430px,104%);height:180px;object-fit:cover;object-position:center 48%;border-radius:26px 26px 12px 12px;opacity:.96;filter:saturate(1.05) contrast(1.03);box-shadow:0 18px 45px #0009,0 0 34px #bb5cff26;border:1px solid #ffffff20}.fauxFounderImage:before{content:''}.fauxFounderTag{position:absolute;right:10px;bottom:4px;padding:6px 9px;border-radius:999px;background:#09040dcf;border:1px solid #ffffff26;color:#fff;font-size:9px;font-weight:900;letter-spacing:.7px;backdrop-filter:blur(10px)}.actionCard>.row,.actionCard>.bigBtn,.actionCard>.footer{position:relative;z-index:2}.bigBtn{box-shadow:0 18px 40px #0008,0 0 32px #ff4fcf4a,0 0 0 1px #ffffff20 inset}.actionCard:after{content:'';position:absolute;left:8%;right:8%;top:-4px;height:2px;background:linear-gradient(90deg,transparent,#62e8ff,#ff4fcf,#ffd56a,transparent);filter:blur(.2px);opacity:.85}.fauxFounderCaption{text-align:center;font-size:9px;color:#ffffff7d;letter-spacing:.6px;margin:-4px 0 9px;position:relative;z-index:2}@media(max-width:420px){.creatorCard{grid-template-columns:68px 1fr}.creatorPhoto{width:68px;height:68px;border-radius:19px}.creatorName{font-size:16px}.actionCard{margin-top:96px}.fauxFounderFrame{height:145px;bottom:70%}.fauxFounderImage{height:154px;width:108%;object-position:center 50%}.fauxFounderTag{right:5px;font-size:8px}}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function addCreatorCard(){const content=$('#content');if(!content||$('#creatorCard'))return;const card=document.createElement('section');card.id='creatorCard';card.className='card creatorCard';card.innerHTML=`<img class="creatorPhoto" src="./assets/rebecca-recline.webp" alt="Rebecca Lynn" onerror="this.onerror=null;this.src='./icons/icon-192.png'"><div><div class="creatorKicker">THE HUMAN BEHIND THE FAUX</div><div class="creatorName">Brought to you by Rebecca Lynn / Fauxbulous</div><div class="creatorSub">Built for people who want better AI image prompts without needing a photography degree, a film crew, or seventeen browser tabs.</div></div>`;const hero=$('.hero');hero?hero.after(card):content.prepend(card)}
function addFounderFrame(){const action=$('.actionCard');if(!action||$('#fauxFounderFrame'))return;const frame=document.createElement('div');frame.id='fauxFounderFrame';frame.className='fauxFounderFrame';frame.innerHTML=`<div class="fauxFounderGlow"></div><img class="fauxFounderImage" src="./assets/rebecca-recline.webp" alt="Rebecca Lynn reclining in a purple editorial look"><div class="fauxFounderTag">REBECCA LYNN · FAUXBULOUS</div>`;action.prepend(frame);const cap=document.createElement('div');cap.className='fauxFounderCaption';cap.textContent='Built by Rebecca Lynn. Powered by big ideas and extremely specific prompts.';const row=action.querySelector('.row');if(row)action.insertBefore(cap,row)}
function addWelcome(){if($('#cheekyWelcome'))return $('#cheekyWelcome');const d=document.createElement('div');d.id='cheekyWelcome';d.className='modal hidden';d.setAttribute('role','dialog');d.setAttribute('aria-modal','true');d.innerHTML=`<div class="modalGlass"><div class="modalTitle center">WELCOME TO FAUXBULOUS ✨</div><div class="cheekyBox">You made it in. Pick a vibe, make questionable creative decisions, and blame the AI if somebody grows a surprise finger. Rebecca has standards. The machines are still learning them. 😏</div><label class="cheekyCheck"><input id="hideCheeky" type="checkbox"> Don’t show this every time</label><button id="cheekyEnter" class="confirmBtn" type="button">LET ME CREATE</button></div>`;document.body.appendChild(d);$('#cheekyEnter').onclick=()=>{if($('#hideCheeky').checked)localStorage.setItem(HIDE_KEY,'1');localStorage.setItem(WELCOME_KEY,'1');d.classList.add('hidden')};return d}
function maybeWelcome(){const d=addWelcome();if(localStorage.getItem(HIDE_KEY)==='1')return;const access=$('#accessModal');const unlocked=!access||access.classList.contains('hidden');if(unlocked&&!localStorage.getItem(WELCOME_KEY))setTimeout(()=>d.classList.remove('hidden'),350)}
window.addEventListener('DOMContentLoaded',()=>{addCreatorCard();addFounderFrame();addWelcome();setTimeout(maybeWelcome,500);const accessBtn=$('#accessEnter');if(accessBtn)accessBtn.addEventListener('click',()=>setTimeout(maybeWelcome,550));});
})();