/* Fauxbulous creator card v20 */
(()=>{'use strict';
const $=(q,r=document)=>r.querySelector(q);
const HIDE_KEY='faux-hide-cheeky-welcome-v1',WELCOME_KEY='faux-cheeky-welcome-seen-v1',CLOSED_KEY='faux-creator-card-closed-v20';
const css=`
.creatorCard{display:grid;grid-template-columns:68px 1fr;gap:11px;align-items:center;position:relative;overflow:hidden;padding-right:42px!important}.creatorPhoto{width:68px;height:68px;border-radius:18px;object-fit:cover;border:1px solid #ffffff2b;box-shadow:0 0 24px #ff4fcf26}.creatorKicker{font-size:8px;letter-spacing:1.35px;color:#ffffff88;font-weight:900}.creatorName{font-size:15px;font-weight:900;margin:2px 0}.creatorSub{font-size:10px;line-height:1.35;color:#ffffffa8}.creatorClose{position:absolute;right:10px;top:10px;width:30px;height:30px;border-radius:999px;border:1px solid #ffffff2d;background:#0008;color:#fff;font-size:17px;line-height:1}.founderMini{margin:4px 0 10px;border:1px solid #ffffff1f;border-radius:18px;overflow:hidden;background:#09040d;position:relative;height:96px}.founderMini img{width:100%;height:100%;object-fit:cover;object-position:center 45%;display:block}.founderMini:after{content:'REBECCA LYNN · FAUXBULOUS';position:absolute;right:8px;bottom:7px;padding:5px 8px;border-radius:999px;background:#08030ddd;border:1px solid #ffffff27;color:#fff;font-size:8px;font-weight:900;letter-spacing:.55px}.cheekyBox{font-size:14px;line-height:1.5;text-align:center;padding:4px 4px 12px}.cheekyCheck{display:flex;align-items:center;justify-content:center;gap:8px;font-size:11px;color:#ffffffa5;margin:10px 0 2px}.cheekyCheck input{width:18px;height:18px;accent-color:#ff53c9}.actionCard{margin-top:0!important;padding-top:15px!important;overflow:hidden!important}.fauxFounderFrame,.fauxFounderCaption,.fauxFounderImage,.fauxFounderGlow,.fauxFounderTag,.founderInline{display:none!important}@media(max-width:390px){.creatorCard{grid-template-columns:58px 1fr;padding-right:38px!important}.creatorPhoto{width:58px;height:58px}.creatorName{font-size:14px}.creatorSub{font-size:9px}.founderMini{height:82px}}
`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function images(){return window.FauxEmbeddedImages||{}}
function removeOldFounder(){document.querySelectorAll('#fauxFounderFrame,.fauxFounderCaption,#founderInline').forEach(x=>x.remove())}
function addCreatorCard(){const content=$('#content');if(!content)return;$('#creatorCard')?.remove();if(localStorage.getItem(CLOSED_KEY)==='1')return;const src=images().creator||'./icons/icon-192.png';const card=document.createElement('section');card.id='creatorCard';card.className='card creatorCard';card.innerHTML=`<button class="creatorClose" type="button" aria-label="Close creator card">×</button><img class="creatorPhoto" alt="" src="${src}"><div><div class="creatorKicker">THE HUMAN BEHIND THE FAUX</div><div class="creatorName">Brought to you by Rebecca Lynn / Fauxbulous</div><div class="creatorSub">Better AI image prompts without needing a photography degree or seventeen browser tabs.</div></div>`;$('.creatorClose',card).onclick=()=>{localStorage.setItem(CLOSED_KEY,'1');card.remove()};const dock=$('#modeDock'),hero=$('.hero');dock?dock.after(card):hero?hero.after(card):content.prepend(card)}
function addFounderMini(){removeOldFounder();$('#founderMini')?.remove();const action=$('.actionCard');if(!action)return;const src=images().recline;if(!src)return;const mini=document.createElement('div');mini.id='founderMini';mini.className='founderMini';mini.innerHTML=`<img alt="" src="${src}">`;action.prepend(mini)}
function addWelcome(){if($('#cheekyWelcome'))return $('#cheekyWelcome');const d=document.createElement('div');d.id='cheekyWelcome';d.className='modal hidden';d.innerHTML=`<div class="modalGlass"><div class="modalTitle center">WELCOME TO FAUXBULOUS ✨</div><div class="cheekyBox">You made it in. Pick a vibe, make questionable creative decisions, and blame the AI if somebody grows a surprise finger. 😏</div><label class="cheekyCheck"><input id="hideCheeky" type="checkbox"> Don’t show this every time</label><button id="cheekyEnter" class="confirmBtn" type="button">LET ME CREATE</button></div>`;document.body.appendChild(d);$('#cheekyEnter').onclick=()=>{if($('#hideCheeky').checked)localStorage.setItem(HIDE_KEY,'1');localStorage.setItem(WELCOME_KEY,'1');d.classList.add('hidden')};return d}
function maybeWelcome(){const d=addWelcome();if(localStorage.getItem(HIDE_KEY)==='1')return;const access=$('#accessModal');if((!access||access.classList.contains('hidden'))&&!localStorage.getItem(WELCOME_KEY))setTimeout(()=>d.classList.remove('hidden'),350)}
function renderVisuals(){removeOldFounder();addCreatorCard();addFounderMini()}
function loadImages(){return new Promise(resolve=>{if(window.FauxEmbeddedImages)return resolve();const old=$('#fauxEmbeddedImages');if(old){old.addEventListener('load',()=>resolve(),{once:true});old.addEventListener('error',()=>resolve(),{once:true});return}const s=document.createElement('script');s.id='fauxEmbeddedImages';s.src='./embedded-images-v20.js?v=20';s.onload=()=>resolve();s.onerror=()=>resolve();document.head.appendChild(s)})}
window.addEventListener('DOMContentLoaded',()=>{addWelcome();loadImages().then(()=>{renderVisuals();setTimeout(renderVisuals,350)});setTimeout(maybeWelcome,500);$('#accessEnter')?.addEventListener('click',()=>setTimeout(maybeWelcome,550))});
})();
