/* AI-FAUXBULOUS Rebecca's Owner Mode v41 */
(()=>{'use strict';
const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)];
const ACCESS_KEY='faux-rebecca-owner-access-v34',VIEW_KEY='faux-rebecca-owner-view-v34',SUITE_KEY='faux-suite-v5',VAULT_KEY='faux-vault-v2';
const params=new URLSearchParams(location.search);if(params.get('owner')==='rebecca'){localStorage.setItem(ACCESS_KEY,'1');localStorage.setItem(VIEW_KEY,'1')}
const hasAccess=()=>localStorage.getItem(ACCESS_KEY)==='1',ownerView=()=>hasAccess()&&localStorage.getItem(VIEW_KEY)!=='0';
const defaults=()=>({strength:3,preset:'',horror:{type:'off',intensity:70,fx:'Detailed',gore:'moderate',seed:''},camera:{focal:'',height:'',framing:'',dof:'',motion:'',stock:''},ref:{on:false,notes:'',lock:true}});
function loadSuite(){let d=defaults();try{const x=JSON.parse(localStorage.getItem(SUITE_KEY)||'{}');d={...d,...x,horror:{...d.horror,...(x.horror||{})},camera:{...d.camera,...(x.camera||{})},ref:{...d.ref,...(x.ref||{})}}}catch{}return d}
function saveSuite(s){localStorage.setItem(SUITE_KEY,JSON.stringify(s));renderSelected()}
const css=`
body:not([data-rebecca-owner="1"]) .fsuite{display:none!important}body[data-rebecca-owner="1"] .fsuite{display:none!important}
#rebeccaOwnerBar,#rebeccaOwnerReturn,#rebeccaCreatorSuite{margin:10px 0 14px;border:1px solid #ffd46f66;border-radius:22px;background:linear-gradient(135deg,#2b1730,#17101d);color:#fff;box-shadow:0 0 24px #ffd46f14}
#rebeccaOwnerBar,#rebeccaOwnerReturn{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:11px 13px}
#rebeccaOwnerBar b,#rebeccaOwnerReturn b{font-size:12px;letter-spacing:.8px}#rebeccaOwnerBar small,#rebeccaOwnerReturn small{display:block;color:#ffffff8c;font-size:9px;margin-top:2px}
#rebeccaOwnerBar button,#rebeccaOwnerReturn button,.rcBtn,.rcPreset,.rcAction{border:1px solid #ffffff24;background:#ffffff0b;color:#fff;border-radius:16px;font-weight:900}
#rebeccaOwnerBar button,#rebeccaOwnerReturn button{padding:9px 11px;font-size:10px;border-radius:999px}
#rebeccaCreatorSuite{padding:14px}.rcTitle{font-size:15px;font-weight:1000;color:#ffd46f;letter-spacing:.8px}.rcSub{font-size:9px;color:#ffffff8c;margin:3px 0 12px}.rcSection{border:1px solid #ffffff18;border-radius:17px;padding:11px;margin:9px 0;background:#07030a66}.rcSection h4{margin:0 0 9px;font-size:11px;letter-spacing:.5px}.rcGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.rcField label{display:block;font-size:9px;color:#ffffff99;margin:0 0 5px}.rcSelect,.rcInput,.rcText{width:100%;box-sizing:border-box;border:1px solid #ffffff25;border-radius:12px;background:#08040d;color:#fff;padding:10px;font-size:14px}.rcText{min-height:68px}.rcRange{width:100%;accent-color:#ff49bf}.rcRow{display:flex;gap:7px;flex-wrap:wrap}.rcPreset,.rcBtn,.rcAction{padding:9px 10px;font-size:9px}.rcPreset.active,.rcBtn.active,.rcAction.active{border-color:#fff;background:linear-gradient(135deg,#ff36b7,#7a55ff);box-shadow:0 0 0 2px #ffffff26,0 0 18px #ff45bf55}.rcStatus{font-size:9px;color:#8fffd3;margin-top:7px;min-height:12px}.rcVaultItem{border:1px solid #ffffff18;border-radius:12px;padding:8px;margin-top:7px;font-size:9px}.rcVaultItem b{display:block;margin-bottom:5px}.rcVaultBtns{display:flex;gap:6px}.rcVaultBtns button{flex:1;border:1px solid #ffffff20;border-radius:999px;background:#ffffff0b;color:#fff;padding:6px;font-size:8px}.rcFilePreview{width:100%;max-height:180px;object-fit:contain;border-radius:12px;margin-top:7px;background:#050208}.hidden{display:none!important}
@media(max-width:520px){.rcGrid{grid-template-columns:1fr}.rcPreset,.rcBtn,.rcAction{font-size:9px}}
`;
function addStyle(){if($('#rebeccaOwnerV41Style'))return;const s=document.createElement('style');s.id='rebeccaOwnerV41Style';s.textContent=css;document.head.appendChild(s)}
function host(){return $('#fauxModeDeck')||$('.hero')}
function clearOwnerUI(){$('#rebeccaOwnerBar')?.remove();$('#rebeccaOwnerReturn')?.remove();$('#rebeccaCreatorSuite')?.remove()}
function setStatus(msg){const e=$('#rcStatus');if(e){e.textContent=msg;clearTimeout(window.__rcStat);window.__rcStat=setTimeout(()=>{if(e)e.textContent=''},1200)}}
function buildBar(){const h=host();if(!h)return;if(ownerView()){const b=document.createElement('div');b.id='rebeccaOwnerBar';b.innerHTML='<div><b>👑 REBECCA\'S OWNER MODE</b><small>Your private creator controls are active.</small></div><button type="button">USER VIEW</button>';b.querySelector('button').onclick=()=>{localStorage.setItem(VIEW_KEY,'0');apply()};h.before(b)}else if(hasAccess()){const b=document.createElement('div');b.id='rebeccaOwnerReturn';b.innerHTML='<div><b>👑 OWNER ACCESS</b><small>You are previewing the regular user app.</small></div><button type="button">OWNER VIEW</button>';b.querySelector('button').onclick=()=>{localStorage.setItem(VIEW_KEY,'1');apply()};h.before(b)}}
function buildSuite(){if(!ownerView())return;const deck=$('#fauxModeDeck');if(!deck)return;const s=loadSuite(),box=document.createElement('section');box.id='rebeccaCreatorSuite';box.innerHTML=`
<div class="rcTitle">👑 REBECCA'S CREATOR SUITE</div><div class="rcSub">These controls are live. Changes save immediately to your Owner app.</div>
<div class="rcSection"><h4>🩸 HORROR LAB</h4><div class="rcGrid"><div class="rcField"><label>Horror engine</label><select id="rcHType" class="rcSelect"><option value="off">Off</option><option value="practical">Practical SFX / Body Horror</option><option value="psychological">Psychological Horror</option><option value="supernatural">Supernatural / Haunted</option><option value="creature">Creature / Monster</option><option value="slasher">Slasher / Practical Gore</option><option value="liminal">Liminal / Uncanny</option><option value="beautiful">Beautiful but Disturbing Editorial</option></select></div><div class="rcField"><label>Gore</label><select id="rcHGore" class="rcSelect"><option value="none">None</option><option value="light">Light movie gore</option><option value="moderate">Moderate practical gore</option><option value="heavy">Heavy fictional practical gore</option></select></div></div><div class="rcField"><label>Intensity: <b id="rcHPct"></b></label><input id="rcHInt" class="rcRange" type="range" min="10" max="100" step="10"></div><div class="rcField"><label>Practical FX detail</label><select id="rcHFx" class="rcSelect"><option>Subtle</option><option>Detailed</option><option>Extreme cinematic</option></select></div><div class="rcField"><label>Fear / story seed</label><textarea id="rcHSeed" class="rcText" placeholder="Mirror reflection moves differently…"></textarea></div></div>
<div class="rcSection"><h4>📸 CAMERA LAB</h4><div class="rcGrid"><div class="rcField"><label>Focal length</label><select id="rcCFocal" class="rcSelect"><option value="">Auto</option><option>14mm ultra-wide</option><option>20mm ultra-wide</option><option>24mm</option><option>28mm</option><option>35mm</option><option>50mm</option><option>70mm</option><option>85mm portrait</option><option>100mm macro</option><option>135mm compression</option></select></div><div class="rcField"><label>Camera height</label><select id="rcCHeight" class="rcSelect"><option value="">Auto</option><option>Floor level</option><option>Knee height</option><option>Waist height</option><option>Chest height</option><option>Eye level</option><option>Above eye level</option><option>Overhead</option></select></div><div class="rcField"><label>Framing</label><select id="rcCFrame" class="rcSelect"><option value="">Auto</option><option>Extreme close-up</option><option>Beauty close-up</option><option>Waist-up</option><option>Three-quarter body</option><option>Full body</option><option>Environmental wide</option></select></div><div class="rcField"><label>Depth of field</label><select id="rcCDof" class="rcSelect"><option value="">Auto</option><option>Very shallow f/1.4</option><option>Shallow f/2</option><option>Balanced f/4</option><option>Deep f/8</option></select></div><div class="rcField"><label>Movement</label><select id="rcCMotion" class="rcSelect"><option value="">Still</option><option>Frozen action</option><option>Subtle handheld realism</option><option>Intentional motion blur</option><option>Paparazzi snap</option></select></div><div class="rcField"><label>Capture</label><select id="rcCStock" class="rcSelect"><option value="">Digital RAW</option><option>Clean full-frame RAW</option><option>35mm color negative</option><option>High-grain 35mm</option><option>Medium-format clarity</option><option>Disposable flash</option></select></div></div></div>
<div class="rcSection"><h4>✨ PROMPT STRENGTH + PRESETS</h4><div class="rcField"><label>Strength: <b id="rcStrengthName"></b></label><input id="rcStrength" class="rcRange" type="range" min="1" max="4" step="1"></div><div class="rcRow" id="rcPresets">${[['baddie','🔥 Baddie'],['glam','✨ Glamour'],['editorial','🖤 Editorial'],['cinematic','🎬 Cinematic'],['fantasy','🔮 Fantasy'],['couple','💞 Couple'],['family','🏡 Family'],['vintage','📼 Vintage'],['horror','🩸 Horror'],['psych','👁 Psychological']].map(x=>`<button type="button" class="rcPreset" data-preset="${x[0]}">${x[1]}</button>`).join('')}</div></div>
<div class="rcSection"><h4>🧬 REFERENCE / ID LOCK</h4><input id="rcRefFile" class="rcInput" type="file" accept="image/*"><img id="rcRefPreview" class="rcFilePreview hidden"><div class="rcField"><label>Identity notes</label><textarea id="rcRefNotes" class="rcText" placeholder="Freckles, tattoos, piercings, body proportions…"></textarea></div><button id="rcRefLock" type="button" class="rcBtn">ABSOLUTE ID LOCK: ON</button></div>
<div class="rcSection"><h4>🗝 PROMPT VAULT</h4><div class="rcRow"><button id="rcVaultSave" class="rcAction" type="button">SAVE CURRENT PROMPT</button><button id="rcVaultRefresh" class="rcAction" type="button">REFRESH VAULT</button></div><div id="rcVaultList"></div></div><div id="rcStatus" class="rcStatus"></div>`;deck.after(box);bindSuite(s);renderVault()}
function bindSuite(s){const strengthNames=['','SIMPLE','DETAILED','CINEMATIC','MAXIMAL'];
const saveH=()=>{s.horror={type:$('#rcHType').value,intensity:+$('#rcHInt').value,fx:$('#rcHFx').value,gore:$('#rcHGore').value,seed:$('#rcHSeed').value.trim()};saveSuite(s);setStatus('Horror settings saved')};
$('#rcHType').value=s.horror.type;$('#rcHInt').value=s.horror.intensity;$('#rcHPct').textContent=s.horror.intensity+'%';$('#rcHFx').value=s.horror.fx;$('#rcHGore').value=s.horror.gore;$('#rcHSeed').value=s.horror.seed;['rcHType','rcHFx','rcHGore','rcHSeed'].forEach(id=>$('#'+id).addEventListener('change',saveH));$('#rcHInt').oninput=e=>{$('#rcHPct').textContent=e.target.value+'%';saveH()};
const cmap={rcCFocal:'focal',rcCHeight:'height',rcCFrame:'framing',rcCDof:'dof',rcCMotion:'motion',rcCStock:'stock'};Object.entries(cmap).forEach(([id,k])=>{const el=$('#'+id);el.value=s.camera[k]||'';el.onchange=()=>{s.camera[k]=el.value;saveSuite(s);setStatus('Camera setting saved')}});
$('#rcStrength').value=s.strength;$('#rcStrengthName').textContent=strengthNames[s.strength];$('#rcStrength').oninput=e=>{s.strength=+e.target.value;$('#rcStrengthName').textContent=strengthNames[s.strength];saveSuite(s);setStatus('Prompt strength saved')};$$('.rcPreset').forEach(b=>{b.classList.toggle('active',b.dataset.preset===s.preset);b.onclick=()=>{s.preset=b.dataset.preset;if(s.preset==='horror'){s.horror.type='practical';s.horror.intensity=85;s.strength=4}if(s.preset==='psych'){s.horror.type='psychological';s.horror.gore='none';s.strength=4}saveSuite(s);$$('.rcPreset').forEach(x=>x.classList.toggle('active',x===b));$('#rcStrength').value=s.strength;$('#rcStrengthName').textContent=strengthNames[s.strength];setStatus('Preset selected: '+b.textContent.trim())}});
$('#rcRefNotes').value=s.ref.notes||'';$('#rcRefLock').classList.toggle('active',s.ref.lock!==false);$('#rcRefLock').textContent='ABSOLUTE ID LOCK: '+(s.ref.lock!==false?'ON':'OFF');$('#rcRefLock').onclick=()=>{s.ref.lock=!(s.ref.lock!==false);$('#rcRefLock').classList.toggle('active',s.ref.lock);$('#rcRefLock').textContent='ABSOLUTE ID LOCK: '+(s.ref.lock?'ON':'OFF');saveSuite(s);setStatus('Identity lock '+(s.ref.lock?'enabled':'disabled'))};$('#rcRefNotes').onchange=()=>{s.ref.notes=$('#rcRefNotes').value.trim();saveSuite(s);setStatus('Identity notes saved')};$('#rcRefFile').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{const img=$('#rcRefPreview');img.src=r.result;img.classList.remove('hidden');s.ref.on=true;saveSuite(s);setStatus('Reference photo selected on this device')};r.readAsDataURL(f)};
$('#rcVaultSave').onclick=()=>saveCurrentPrompt();$('#rcVaultRefresh').onclick=()=>renderVault();}
function renderSelected(){const s=loadSuite();$$('.rcPreset').forEach(b=>b.classList.toggle('active',b.dataset.preset===s.preset))}
function vault(){try{return JSON.parse(localStorage.getItem(VAULT_KEY)||'[]')}catch{return[]}}
function setVault(v){localStorage.setItem(VAULT_KEY,JSON.stringify(v))}
function saveCurrentPrompt(){const text=$('#promptText')?.value?.trim();if(!text){setStatus('Generate a prompt first, then save it');return}const v=vault();v.unshift({title:'Fauxbulous Prompt '+new Date().toLocaleDateString(),prompt:text,ts:Date.now()});setVault(v.slice(0,250));renderVault();setStatus('Prompt saved to Vault')}
function renderVault(){const list=$('#rcVaultList');if(!list)return;const v=vault();list.innerHTML=v.length?'':'<div class="rcStatus">No saved prompts yet.</div>';v.slice(0,20).forEach((it,i)=>{const d=document.createElement('div');d.className='rcVaultItem';d.innerHTML=`<b>${(it.title||'Saved Prompt').replace(/[<>]/g,'')}</b><div class="rcVaultBtns"><button type="button">COPY</button><button type="button">DELETE</button></div>`;const [copy,del]=d.querySelectorAll('button');copy.onclick=async()=>{try{await navigator.clipboard.writeText(it.prompt||it.text||'');setStatus('Copied from Vault')}catch{setStatus('Copy failed')}};del.onclick=()=>{const all=vault();all.splice(i,1);setVault(all);renderVault();setStatus('Deleted from Vault')};list.appendChild(d)})}
function apply(){clearOwnerUI();document.body.dataset.rebeccaOwner=ownerView()?'1':'0';buildBar();buildSuite()}
function boot(){addStyle();apply();setTimeout(()=>{if(!$('#rebeccaCreatorSuite')&&ownerView())apply()},500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();