/* Fauxbulous Spicy Mode v21 — boudoir only */
(()=>{'use strict';
const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)];
const MODE_KEY='faux-ui-mode-v1',STATE_KEY='ai-fauxbulous-state-v4';
const css=`body[data-faux-mode="spicy"] #scrapToggle,body[data-faux-mode="spicy"] #scrapFields,body[data-faux-mode="spicy"] .field:has(#scrapToggle),body[data-faux-mode="spicy"] [data-pick="scrapStyle"],body[data-faux-mode="spicy"] [data-pick="scrapElements"]{display:none!important}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function getMode(){return localStorage.getItem(MODE_KEY)||'normal'}
function syncCoreSpicy(){try{const s=JSON.parse(localStorage.getItem(STATE_KEY)||'{}');const on=getMode()==='spicy';s.spicy=on;if(on&&s.global){s.global.scrapbookOn=false;s.global.scrapbookLevel='None';s.global.scrapStyle='';s.global.scrapElements=''}localStorage.setItem(STATE_KEY,JSON.stringify(s));const toggle=$('#spicyToggle');if(toggle){const pressed=toggle.getAttribute('aria-pressed')==='true';if(on!==pressed)toggle.click()}}catch{}}
function cleanSpicyUI(){if(getMode()==='spicy'){const scrap=$('#scrapToggle');if(scrap?.getAttribute('aria-pressed')==='true')scrap.click()}}
function enhanceSpicyPrompt(){if(getMode()!=='spicy')return;const ta=$('#promptText');if(!ta?.value)return;let t=ta.value;
  t=t.replace(/- Scrapbook styling:[^\n]*\n?/gi,'').replace(/- Scrapbook theme:[^\n]*\n?/gi,'').replace(/- Scrapbook elements:[^\n]*\n?/gi,'').replace(/- Scrapbook materials[^\n]*\n?/gi,'');
  const block=`\n\nSPICY MODE — STRICT ADULT BOUDOIR OVERRIDE:\n- This mode is BOUDOIR ONLY. The finished image must immediately read as a sexy, clearly adult boudoir photograph, never ordinary fashion, lifestyle, workplace, daytime streetwear, bakery, office, casual portrait, or generic editorial.\n- If any earlier scene, wardrobe, pose, mood, or prop conflicts with boudoir, OVERRIDE it rather than trying to preserve it.\n- Use one sophisticated adult boudoir concept such as satin-bed glamour, lace lingerie editorial, corset boudoir, opaque bodysuit, stockings and garters over full coverage, silk robe, leather-luxe boudoir, velvet chaise, hotel-suite boudoir, dressing-room mirror, bed-edge pose, reclining floor pose, kneeling editorial pose, chair pose, dark feminine boudoir, pin-up glamour, shower-steam glamour with full coverage, candlelit bedroom glamour, black-studio boudoir, or luxury penthouse boudoir.\n- Wardrobe must be sensual boudoir styling: lingerie-inspired fashion, corsetry, satin, lace, velvet, fitted bodysuits, slips, robes, stockings, sculpted bra-style tops with opaque coverage, or similarly sexy adult wardrobe. No normal blouse-and-pants outfit, officewear, sportswear, novelty costume, childish onesie, or everyday daytime clothing.\n- Pose must feel intentionally sexy and photographic: arched reclining posture, seated hip-shift, bed-edge pose, kneeling pose, floor pose, over-shoulder body line, chair-straddle editorial pose while clothed, robe slipping from one shoulder with coverage, hand at thigh/waist/hair, or other mature sensual body language.\n- Use bedroom, luxury suite, boudoir studio, velvet lounge, dressing room, private penthouse, steamy tiled room, dark studio, or another unmistakably adult intimate setting.\n- Lighting should flatter skin and curves: moody window light, warm bedside practicals, candlelight, softbox beauty light, rim light, low-key side light, or glossy nightlife-style boudoir lighting.\n- Make the image sexy through expression, pose, wardrobe, body language, camera placement, fabric texture and atmosphere.\n- Clearly adult only. No youthful styling, childish props, scrapbook elements, school aesthetics, nudity, exposed nipples/genitals, explicit sexual activity, fetishized coercion, or pornographic framing.`;
  t=t.replace(/\n\nSPICY MODE[^\n]*[\s\S]*?(?=\n\n#rebeccalynndeulen|$)/i,'');
  ta.value=t.trimEnd()+block;
}
function modeChanged(){syncCoreSpicy();setTimeout(cleanSpicyUI,0)}
window.addEventListener('DOMContentLoaded',()=>{setTimeout(()=>{syncCoreSpicy();cleanSpicyUI();$$('.modeBtn').forEach(b=>b.addEventListener('click',()=>setTimeout(modeChanged,0)));const go=$('#goBtn');if(go)go.addEventListener('click',()=>[70,180,360].forEach(ms=>setTimeout(enhanceSpicyPrompt,ms)))},80)});
})();