/* AI-FAUXBULOUS stable mode + horror engine v20 */
(()=>{'use strict';
const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)];
const MODE_KEY='faux-ui-mode-v1',HORROR_KEY='faux-horror-surprise-v20';
let mode=localStorage.getItem(MODE_KEY)||'normal';
const HORROR_BUNDLES=[
'PRACTICAL SFX BODY HORROR: The adult subject is mid-transformation with believable silicone and latex prosthetic appliances, subtle torn-skin seams, bruising, translucent edges, stage blood and practical slime. The horror must visibly affect the body or face, not sit in the background as a prop. Use tactile wetness, gravity, compression, pores and imperfect appliance edges. Beautiful but deeply disturbing.',
'PSYCHOLOGICAL HORROR: A familiar room is visibly wrong. The adult subject notices that every reflection shows a slightly different expression and one reflection is looking directly at the camera. Use negative space, impossible continuity, restrained dread and one unmistakable visual contradiction. No random gore required.',
'HAUNTED POSSESSION: The clearly adult subject is caught during a physically believable possession event. Practical contact-lens eye effect, strained facial muscles, unnatural but anatomically plausible posture, subtle vascular discoloration, moving curtains with no wind source, and a dark humanlike presence just outside the key light. Keep it photographic, not fantasy CGI.',
'SLASHER AFTERMATH: The clearly adult subject has escaped a violent fictional movie-horror encounter. Torn wardrobe, practical stage blood, realistic bruising and abrasions, flashlight or emergency light, breathless defensive posture, and a threatening silhouette in the distance. The danger must be obvious at first glance.',
'CREATURE ENCOUNTER: A practical creature is physically sharing the scene with the adult subject. Use animatronic/puppet realism, imperfect organic texture, saliva threads, weight on surfaces, contact shadows and believable interaction. The subject reacts to the creature, not posing calmly beside it.',
'LIMINAL NIGHTMARE: The adult subject is isolated inside architecture that repeats incorrectly. Hallways stretch too long, exit signs point both directions, doors recur with impossible numbering, and a distant figure appears closer in every reflection. Clean composition, cold practical lighting, severe unease.',
'BEAUTIFUL BUT DISTURBING EDITORIAL: High-fashion horror where couture beauty is fused with practical macabre detail. Gorgeous styling and controlled pose, but one unmistakably horrifying centerpiece such as a realistic prosthetic facial split, impossible duplicate hand, living shadow, or organic growth integrated into the wardrobe. Elegant, photorealistic, unnerving.',
'MEDICAL / INSTITUTIONAL HORROR: The adult subject is in an abandoned clinical environment under flickering fluorescent light. Practical medical props, condensation, smeared floor reflections, restrained body-horror prosthetics and signs that a procedure stopped halfway through. Avoid clean sci-fi labs and avoid normal hospital portrait energy.'
];
const css=`
:root{--modeA:#ff5bd8;--modeB:#7d6cff;--modeGlow:#ff5bd844}
body[data-faux-mode="horror"]{--modeA:#e01d43;--modeB:#611126;--modeGlow:#e01d4355;background:radial-gradient(circle at 50% 0,#3b0713,#0b0205 48%,#050204)!important}body[data-faux-mode="spicy"]{--modeA:#ff3b92;--modeB:#9e174f;--modeGlow:#ff3b9255;background:radial-gradient(circle at 50% 0,#4a092c,#100207 52%,#050204)!important}
.modeDock{position:relative;z-index:10;margin:10px 0 14px;padding:9px;border:1px solid #ffffff20;border-radius:19px;background:#0a050ded;box-shadow:0 10px 30px #0007}.modeBtns{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.modeBtn{border:1px solid #ffffff26;border-radius:14px;background:#ffffff09;color:#fff;padding:11px 5px;font-size:10px;font-weight:950;letter-spacing:.55px}.modeBtn.active{border-color:var(--modeA);background:linear-gradient(135deg,var(--modeA),var(--modeB));box-shadow:0 0 20px var(--modeGlow)}.modeTools{display:grid;grid-template-columns:1.15fr 1fr 1fr;gap:6px;margin-top:7px}.modeTools button{border:1px solid #ffffff1f;border-radius:999px;background:#ffffff08;color:#fff;padding:8px 4px;font-size:8px;font-weight:900}.modeHint{font-size:9px;text-align:center;color:#ffffff8c;margin-top:7px;font-weight:800;line-height:1.35}
body[data-faux-mode="horror"] .card{border-color:#7f1930!important;background:linear-gradient(180deg,#1a070c,#090306)!important}body[data-faux-mode="spicy"] .card{border-color:#76204e!important;background:linear-gradient(180deg,#220815,#0a0307)!important}body[data-faux-mode="horror"] .bigBtn{background:linear-gradient(135deg,#e01d43,#691327)!important;color:#fff!important}body[data-faux-mode="spicy"] .bigBtn{background:linear-gradient(135deg,#ff3b92,#a41455)!important;color:#fff!important}
.stableCollapsible{padding-top:12px}.stableSectionToggle{width:100%;display:flex;align-items:center;justify-content:space-between;gap:8px;border:0;background:transparent;color:#fff;padding:0 0 9px;font-size:12px;font-weight:950;letter-spacing:.6px;text-align:left}.stableSectionToggle small{font-size:9px;color:#ffffff70;font-weight:700}.stableSectionToggle .chev{font-size:16px}.stableCollapsible.collapsed>.stableBody{display:none}.stableCollapsible.collapsed .chev{transform:rotate(-90deg)}#spicyToggle,#spicyNote{display:none!important}.legacyModeCard{display:none!important}
@media(max-width:600px){.modeBtn{padding:10px 3px}.modeTools button{font-size:7px;padding:8px 3px}.fx{animation:none!important;transform:none!important}}
`;
function addCss(){if($('#stableV20Css'))return;const s=document.createElement('style');s.id='stableV20Css';s.textContent=css;document.head.appendChild(s)}
function setMode(next){mode=next;localStorage.setItem(MODE_KEY,next);document.body.dataset.fauxMode=next;$$('.modeBtn').forEach(b=>b.classList.toggle('active',b.dataset.mode===next));const go=$('#goBtn');if(go)go.textContent=next==='horror'?'SCARE ME':next==='spicy'?'MAKE IT SPICY':'GET FAUXBULOUS';const hint=$('#modeHint');if(hint)hint.textContent=next==='horror'?'HORROR MODE · horror must dominate the image, not just add a spooky prop':next==='spicy'?'SPICY MODE · clearly adult, sultry, luxe, non-explicit':'NORMAL MODE · glam, editorial, cinematic, creative';const old=$('#spicyToggle');if(old){const on=old.getAttribute('aria-pressed')==='true';if(next==='spicy'&&!on)old.click();if(next!=='spicy'&&on)old.click()}if(next==='spicy'||next==='horror'){const scrap=$('#scrapToggle');if(scrap?.getAttribute('aria-pressed')==='true')scrap.click()}}
function surpriseAll(){const legacy=$('#modeSurprise');legacy?.click();if(mode==='horror'){localStorage.setItem(HORROR_KEY,HORROR_BUNDLES[Math.floor(Math.random()*HORROR_BUNDLES.length)])}else localStorage.removeItem(HORROR_KEY);setMode(mode)}
function modeDock(){if($('#modeDock'))return;const hero=$('.hero');if(!hero)return;const d=document.createElement('section');d.id='modeDock';d.className='modeDock';d.innerHTML=`<div class="modeBtns"><button type="button" class="modeBtn" data-mode="normal">✨ NORMAL</button><button type="button" class="modeBtn" data-mode="horror">👁 HORROR</button><button type="button" class="modeBtn" data-mode="spicy">🔥 SPICY</button></div><div class="modeTools"><button id="surpriseEverything" type="button">🎲 SURPRISE EVERYTHING</button><button id="collapseAll" type="button">COLLAPSE ALL</button><button id="expandAll" type="button">EXPAND ALL</button></div><div id="modeHint" class="modeHint"></div>`;hero.after(d);$$('.modeBtn',d).forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#surpriseEverything').onclick=surpriseAll;$('#collapseAll').onclick=()=>$$('.stableCollapsible').forEach(c=>c.classList.add('collapsed'));$('#expandAll').onclick=()=>$$('.stableCollapsible').forEach(c=>c.classList.remove('collapsed'));setMode(mode)}
function legacyCleanup(){const m=$$('.card').find(c=>$('.cardTitle',c)?.textContent.trim()==='Mode');if(m)m.classList.add('legacyModeCard')}
function makeCollapsible(card,label){if(!card||card.dataset.stableDone)return;card.dataset.stableDone='1';card.classList.add('stableCollapsible','collapsed');const original=[...card.children],body=document.createElement('div');body.className='stableBody';original.forEach(n=>body.appendChild(n));const head=document.createElement('button');head.type='button';head.className='stableSectionToggle';head.innerHTML=`<span>${label}</span><small>tap to open</small><span class="chev">⌄</span>`;head.onclick=()=>card.classList.toggle('collapsed');card.append(head,body)}
function collapsibles(){const cards=$$('.card'),people=cards.find(c=>$('.cardTitle',c)?.textContent.trim()==='People Setup');makeCollapsible(people,'WHO / SUBJECT');makeCollapsible($('#personCard'),'LOOK + WARDROBE');makeCollapsible($('#sceneCard'),'SCENE + CAMERA + LIGHTING');const suite=$('.fsuite');if(suite)makeCollapsible(suite,'CREATOR TOOLS / MODE DETAILS')}
function cleanTag(s){return String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9]/g,'').slice(0,45)}
function smartTags(text){const rules=mode==='horror'?[[/psychological|liminal|reflection/i,'#PsychologicalHorror'],[/prosthetic|practical sfx|stage blood|body horror/i,'#PracticalHorror'],[/haunted|possession/i,'#HauntedHorror'],[/slasher/i,'#SlasherHorror'],[/creature/i,'#CreatureHorror'],[/./,'#CinematicHorror']]:mode==='spicy'?[[/boudoir|sultry|sensual/i,'#SultryEditorial'],[/fashion|editorial|couture/i,'#FashionEditorial'],[/./,'#AfterDarkGlam']]:[[/fashion|editorial|couture/i,'#FashionEditorial'],[/glam|beauty|makeup/i,'#GlamPortrait'],[/cinematic|35mm|film/i,'#CinematicPortrait'],[/./,'#UltraPhotorealistic']];const out=[];for(const [r,t] of rules){if(r.test(text)&&!out.includes(t))out.push(t);if(out.length===2)break}while(out.length<2)out.push('#CreativePortrait');return out.slice(0,2)}
function finishPrompt(){const ta=$('#promptText');if(!ta||!ta.value.trim())return;let text=ta.value.replace(/\n*#rebeccalynndeulen\s+#[A-Za-z0-9]+\s+#AIFauxbulous\s+#[A-Za-z0-9]+\s+#[A-Za-z0-9]+\s*$/i,'').trimEnd();if(mode==='horror'){const bundle=localStorage.getItem(HORROR_KEY)||HORROR_BUNDLES[Math.floor(Math.random()*HORROR_BUNDLES.length)];text+='\n\nHORROR MODE — CENTRAL CONCEPT OVERRIDE:\n'+bundle+'\n- CRITICAL: The finished image must read immediately and unmistakably as HORROR before the viewer notices fashion, weather, location, or props. Horror is the central event, not decoration.\n- If earlier choices create an ordinary lifestyle/fashion scene, reinterpret them through this horror concept instead of preserving a normal mood.\n- Do NOT make a normal portrait with only a creepy book, bone, skull, dark makeup, rain, or background silhouette.\n- Use practical photographic realism, dimensional shadows, believable anatomy, tactile materials and a clear reaction/interaction between the adult subject and the horror event.\n- No cartoon, illustration, glossy CGI monster, videogame look or generic Halloween costume.'}if(mode==='spicy')text+='\n\nSPICY MODE — ADULT EDITORIAL OVERRIDE:\nCreate one clearly adult, ultra-photorealistic sultry fashion editorial. Prioritize confident mature body language, fitted luxe wardrobe, strong eye contact, flattering directional light, sophisticated after-dark atmosphere and sensual but non-explicit posing. No childish scrapbook styling, stickers, school aesthetics, toys, nudity or sexual acts.';const sig=cleanTag(localStorage.getItem('faux-personal-signature-v1')||'Rebecca Lynn')||'RebeccaLynn';const tags=['#rebeccalynndeulen','#'+sig,'#AIFauxbulous',...smartTags(text)];ta.value=text+'\n\n'+tags.slice(0,5).join(' ')}
function wireGenerate(){const go=$('#goBtn');if(!go||go.dataset.v20Wired)return;go.dataset.v20Wired='1';go.addEventListener('click',()=>[35,120,280].forEach(ms=>setTimeout(finishPrompt,ms)))}
function boot(){addCss();modeDock();legacyCleanup();collapsibles();wireGenerate();setMode(mode)}
window.addEventListener('DOMContentLoaded',()=>{setTimeout(boot,80);setTimeout(boot,500)});
})();
