/* AI-FAUXBULOUS smart builder v12 */
(()=>{'use strict';
const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)];
const MODE_KEY='faux-ui-mode-v1',LOCK_KEY='faux-section-locks-v1',INSPO_KEY='faux-inspo-v1',HEAT_KEY='faux-spicy-heat-v1';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const rand=a=>a[Math.floor(Math.random()*a.length)];
const css=`
:root{--modeA:#ff5bd8;--modeB:#7d6cff;--modeC:#44d9ff;--modeGlow:#ff5bd844}
body[data-faux-mode="horror"]{--modeA:#d80f36;--modeB:#64112e;--modeC:#a68b99;--modeGlow:#d80f3655;background-color:#090307}
body[data-faux-mode="spicy"]{--modeA:#ff3b92;--modeB:#a30d49;--modeC:#e9b852;--modeGlow:#ff3b9255;background-color:#120308}
.modeDock{position:sticky;top:6px;z-index:45;padding:8px;border:1px solid #ffffff22;border-radius:20px;background:#0b0610e8;backdrop-filter:blur(18px);box-shadow:0 10px 35px #0007;margin-bottom:10px}.modeBtns{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.modeBtn{border:1px solid #ffffff2c;background:#ffffff09;color:#fff;border-radius:15px;padding:12px 6px;font-size:11px;font-weight:900;letter-spacing:.7px}.modeBtn.active{border-color:var(--modeA);background:linear-gradient(135deg,var(--modeA),var(--modeB));box-shadow:0 0 22px var(--modeGlow)}.modeMini{display:flex;gap:6px;margin-top:7px}.modeMini button{flex:1;border:1px solid #ffffff1f;border-radius:99px;background:#ffffff08;color:#ffffffaa;padding:7px;font-size:9px;font-weight:800}
.smartSection{overflow:hidden;transition:border-color .2s,box-shadow .2s}.smartSection.sectionOpen{border-color:color-mix(in srgb,var(--modeA) 45%,transparent);box-shadow:0 0 25px var(--modeGlow)}.smartHead{display:flex;align-items:center;gap:8px}.smartHead .cardTitle{margin:0;flex:1}.smartChevron{border:0;background:transparent;color:#fff;font-size:19px;padding:4px 2px}.smartSummary{font-size:9px;color:#ffffff77;white-space:nowrap;max-width:44%;overflow:hidden;text-overflow:ellipsis}.smartBody{padding-top:10px}.smartSection.sectionCollapsed .smartBody{display:none}.smartSection.sectionCollapsed .smartChevron{transform:rotate(-90deg)}.sectionTools{display:grid;grid-template-columns:1fr .72fr .62fr;gap:6px;margin-top:12px;padding-top:10px;border-top:1px solid #ffffff14}.sectionTools button{border:1px solid #ffffff23;border-radius:99px;background:#ffffff08;color:#fff;padding:8px 5px;font-size:9px;font-weight:900}.sectionTools .surprise{border-color:var(--modeA);box-shadow:0 0 13px var(--modeGlow)}.sectionTools .locked{background:var(--modeA);color:#140510}.smartHidden{display:none!important}.modeNotice{font-size:10px;line-height:1.45;color:#ffffffb0;padding:10px;border:1px solid #ffffff18;border-radius:13px;background:#ffffff06;margin:8px 0}.inspoGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:8px}.inspoThumb{aspect-ratio:1;border-radius:12px;overflow:hidden;border:1px solid #ffffff20;background:#0007;position:relative}.inspoThumb img{width:100%;height:100%;object-fit:cover}.inspoThumb button{position:absolute;right:4px;top:4px;border:0;border-radius:99px;background:#000b;color:#fff;width:25px;height:25px}.inspoChecks{display:grid;grid-template-columns:repeat(2,1fr);gap:5px;margin-top:9px}.inspoChecks label{font-size:9px;color:#ffffffb5;display:flex;gap:5px;align-items:center}.smartInput{width:100%;box-sizing:border-box;border:1px solid #ffffff24;border-radius:13px;background:#0004;color:#fff;padding:10px;font-size:14px}.modeLoading{position:fixed;inset:0;z-index:300;display:flex;align-items:center;justify-content:center;background:#030104dd;backdrop-filter:blur(12px)}.modeLoading>div{padding:24px 28px;border:1px solid var(--modeA);border-radius:22px;background:#100711;text-align:center;font-weight:900;box-shadow:0 0 45px var(--modeGlow)}.modeLoading small{display:block;margin-top:7px;color:#ffffff88;font-size:10px}.modeLoading.hidden{display:none}.modeChip{font-size:9px;color:var(--modeC);font-weight:900;margin-top:5px}.bigBtn{background:linear-gradient(135deg,var(--modeA),var(--modeB))!important;box-shadow:0 12px 35px var(--modeGlow)!important}.confirmBtn{background:linear-gradient(135deg,var(--modeA),var(--modeB))!important}.pill.active,.segBtn.active,.toggleBtn[aria-pressed="true"]{border-color:var(--modeA)!important;box-shadow:0 0 14px var(--modeGlow)!important}.fx1,.fx2,.fx3{filter:hue-rotate(var(--modeHue,0deg))}.wardrobeNote{font-size:9px;color:#ffffff77;margin-top:6px}
@media(max-width:520px){.modeDock{top:4px}.modeBtn{padding:10px 3px;font-size:10px}.smartSummary{max-width:36%}.sectionTools{grid-template-columns:1fr .7fr .6fr}.inspoGrid{grid-template-columns:repeat(3,1fr)}}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
let mode=localStorage.getItem(MODE_KEY)||'normal';let locks={};try{locks=JSON.parse(localStorage.getItem(LOCK_KEY)||'{}')}catch{}
const sections={};
function cardTitleText(card){return $('.cardTitle',card)?.textContent.trim()||''}
function getCoreState(){try{return JSON.parse(localStorage.getItem('ai-fauxbulous-state-v4')||'{}')}catch{return {}}}
function setCoreState(s){localStorage.setItem('ai-fauxbulous-state-v4',JSON.stringify(s))}
function fieldForPick(k){const b=$(`[data-pick="${k}"]`);return b?.closest('.field')||null}
function selected(k){const b=$(`[data-pick="${k}"]`);if(!b)return '';const t=b.textContent.trim();return /^(Pick|Select|Choose|Blank)/i.test(t)?'':t}
function makeCard(name,id){const c=document.createElement('section');c.className='card smartSection sectionCollapsed';c.dataset.section=id;c.innerHTML=`<div class="smartHead"><button class="smartChevron" type="button">⌄</button><div class="cardTitle">${name}</div><div class="smartSummary">Not set</div></div><div class="smartBody"></div>`;return c}
function toolRow(id,customLabel='SURPRISE ME'){const d=document.createElement('div');d.className='sectionTools';d.innerHTML=`<button class="surprise" type="button">🎲 ${customLabel}</button><button class="clearSection" type="button">CLEAR</button><button class="lockSection" type="button">🔓 LOCK</button>`;$('.surprise',d).onclick=()=>surpriseSection(id);$('.clearSection',d).onclick=()=>clearSection(id);$('.lockSection',d).onclick=()=>toggleLock(id);return d}
function prepareSection(card,id,name,open=false,surpriseLabel='SURPRISE ME'){card.dataset.section=id;card.classList.add('smartSection');let old=$('.cardTitle',card);let children=[...card.children];const head=document.createElement('div');head.className='smartHead';const chev=document.createElement('button');chev.className='smartChevron';chev.type='button';chev.textContent='⌄';const title=old||document.createElement('div');title.className='cardTitle';title.textContent=name;const sum=document.createElement('div');sum.className='smartSummary';sum.textContent='Not set';head.append(chev,title,sum);const body=document.createElement('div');body.className='smartBody';children.forEach(ch=>{if(ch!==old)body.appendChild(ch)});body.appendChild(toolRow(id,surpriseLabel));card.replaceChildren(head,body);if(!open)card.classList.add('sectionCollapsed');else card.classList.add('sectionOpen');chev.onclick=()=>toggleSection(card);head.onclick=e=>{if(e.target===head||e.target===title||e.target===sum)toggleSection(card)};sections[id]=card;updateLockButton(id);return body}
function toggleSection(card){card.classList.toggle('sectionCollapsed');card.classList.toggle('sectionOpen',!card.classList.contains('sectionCollapsed'))}
function toggleLock(id){locks[id]=!locks[id];localStorage.setItem(LOCK_KEY,JSON.stringify(locks));updateLockButton(id)}
function updateLockButton(id){const b=$('.lockSection',sections[id]);if(!b)return;b.classList.toggle('locked',!!locks[id]);b.textContent=locks[id]?'🔒 LOCKED':'🔓 LOCK'}
function moveField(key,to){const f=fieldForPick(key);if(f)to.appendChild(f)}
function moveById(id,to){const e=$('#'+id);const f=e?.closest('.field')||e;if(f)to.appendChild(f)}
function restructure(){
  const content=$('#content');if(!content||$('#modeDock'))return;
  const hero=$('.hero');const spicy=$('#spicyToggle');if(spicy)spicy.classList.add('smartHidden');const note=$('#spicyNote');if(note)note.classList.add('smartHidden');
  const modeDock=document.createElement('section');modeDock.id='modeDock';modeDock.className='modeDock';modeDock.innerHTML=`<div class="modeBtns"><button class="modeBtn" data-mode="normal">✨ NORMAL</button><button class="modeBtn" data-mode="horror">👁 HORROR</button><button class="modeBtn" data-mode="spicy">🔥 SPICY</button></div><div class="modeMini"><button id="surpriseAll">🎲 SURPRISE EVERYTHING</button><button id="collapseAll">COLLAPSE ALL</button><button id="expandAll">EXPAND ALL</button></div><div id="modeChip" class="modeChip"></div>`;hero.after(modeDock);$$('.modeBtn',modeDock).forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#surpriseAll').onclick=surpriseEverything;$('#collapseAll').onclick=()=>Object.values(sections).forEach(c=>{c.classList.add('sectionCollapsed');c.classList.remove('sectionOpen')});$('#expandAll').onclick=()=>Object.values(sections).forEach(c=>{c.classList.remove('sectionCollapsed');c.classList.add('sectionOpen')});
  const oldMode=$$('.card',content).find(c=>cardTitleText(c)==='Mode');if(oldMode)oldMode.classList.add('smartHidden');
  const people=$$('.card',content).find(c=>cardTitleText(c)==='People Setup');const person=$('#personCard'),scene=$('#sceneCard');if(!people||!person||!scene)return;
  prepareSection(people,'who','WHO',true);
  const personBody=$('.stack',person)||person;const divider=$('.cardDivider',personBody);const look=makeCard('LOOK','look'),ward=makeCard('WARDROBE','wardrobe');const lookBody=$('.smartBody',look),wardBody=$('.smartBody',ward);let after=false;[...personBody.children].forEach(ch=>{if(ch===divider){after=true;return}(after?wardBody:lookBody).appendChild(ch)});person.remove();lookBody.appendChild(toolRow('look'));wardBody.appendChild(document.createRange().createContextualFragment('<div class="wardrobeNote">Choosing a dress, onesie, costume, or separates automatically hides conflicting outfit paths.</div>'));wardBody.appendChild(toolRow('wardrobe'));wireNewCard(look,'look');wireNewCard(ward,'wardrobe');people.after(look,ward);
  const sceneNew=makeCard('SCENE','scene'),camera=makeCard('CAMERA','camera'),lighting=makeCard('LIGHTING','lighting'),extras=makeCard('EXTRAS','extras');const sb=$('.smartBody',sceneNew),cb=$('.smartBody',camera),lb=$('.smartBody',lighting),eb=$('.smartBody',extras);
  ['sceneIO','environment','timeOfDay','weather','mood'].forEach(k=>moveField(k,sb));['cameraAngle','lens'].forEach(k=>moveField(k,cb));moveField('lighting',lb);
  const scrap=$('#scrapToggle')?.closest('.field');const scrapFields=$('#scrapFields');if(scrap)eb.appendChild(scrap);if(scrapFields)eb.appendChild(scrapFields);
  ['namesOnImg','dateOnImg','sigOnImg','layoutPick'].forEach(id=>moveById(id,eb));
  sb.appendChild(toolRow('scene'));cb.appendChild(toolRow('camera'));lb.appendChild(toolRow('lighting'));eb.appendChild(toolRow('extras'));[sceneNew,camera,lighting,extras].forEach((c,i)=>wireNewCard(c,['scene','camera','lighting','extras'][i]));scene.replaceWith(sceneNew,camera,lighting);
  const suite=$('.fsuite');if(suite){prepareSection(suite,'details','MODE DETAILS',false);lighting.after(suite)}
  const inspo=buildInspo();(suite||lighting).after(inspo,extras);
  const action=$('.actionCard');if(action){const r=$('#rerollBtn');if(r)r.classList.add('smartHidden')}
  updateMode();updateSummaries();updateContradictions();
}
function wireNewCard(card,id){const head=$('.smartHead',card),chev=$('.smartChevron',card),title=$('.cardTitle',card),sum=$('.smartSummary',card);sections[id]=card;chev.onclick=()=>toggleSection(card);head.onclick=e=>{if(e.target===head||e.target===title||e.target===sum)toggleSection(card)};updateLockButton(id)}
function buildInspo(){const c=makeCard('INSPO / CREATIVE DIRECTION','inspo'),b=$('.smartBody',c);b.innerHTML=`<div class="modeNotice">Add up to 6 inspiration images. These guide style only, never identity. Upload the same images with the finished prompt in your image generator.</div><input id="inspoFiles" class="smartInput" type="file" accept="image/*" multiple><div id="inspoGrid" class="inspoGrid"></div><div class="inspoChecks">${['Overall vibe','Pose','Hair','Makeup','Outfit','Color palette','Lighting','Camera / composition','Environment','Texture / materials'].map((x,i)=>`<label><input type="checkbox" data-inspo="${x}" ${i<4?'checked':''}> ${x}</label>`).join('')}</div>`;b.appendChild(toolRow('inspo','SURPRISE DIRECTION'));wireNewCard(c,'inspo');$('#inspoFiles',c).onchange=loadInspoFiles;$$('[data-inspo]',c).forEach(x=>x.onchange=saveInspoMeta);renderInspo();return c}
function loadInspoFiles(e){const files=[...e.target.files].slice(0,6);Promise.all(files.map(f=>new Promise(res=>{const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(f)}))).then(arr=>{let meta=getInspo();meta.images=arr;saveInspo(meta);renderInspo()})}
function getInspo(){try{return Object.assign({images:[],aspects:['Overall vibe','Pose','Hair','Makeup']},JSON.parse(localStorage.getItem(INSPO_KEY)||'{}'))}catch{return {images:[],aspects:[]}}}
function saveInspo(m){localStorage.setItem(INSPO_KEY,JSON.stringify(m))}
function saveInspoMeta(){const m=getInspo();m.aspects=$$('[data-inspo]',sections.inspo).filter(x=>x.checked).map(x=>x.dataset.inspo);saveInspo(m);updateSummaries()}
function renderInspo(){if(!sections.inspo)return;const m=getInspo(),g=$('#inspoGrid',sections.inspo);g.innerHTML='';m.images.forEach((src,i)=>{const d=document.createElement('div');d.className='inspoThumb';d.innerHTML=`<img src="${src}" alt="Inspiration ${i+1}"><button type="button">✕</button>`;$('button',d).onclick=()=>{const x=getInspo();x.images.splice(i,1);saveInspo(x);renderInspo()};g.appendChild(d)});$$('[data-inspo]',sections.inspo).forEach(x=>x.checked=m.aspects.includes(x.dataset.inspo));updateSummaries()}
function setMode(m){mode=m;localStorage.setItem(MODE_KEY,m);const spicy=$('#spicyToggle');const on=spicy?.getAttribute('aria-pressed')==='true';if(m==='spicy'&&!on)spicy?.click();if(m!=='spicy'&&on)spicy?.click();updateMode()}
function updateMode(){document.body.dataset.fauxMode=mode;$$('.modeBtn').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));const go=$('#goBtn'),chip=$('#modeChip');if(go)go.textContent=mode==='horror'?'SCARE ME':mode==='spicy'?'MAKE IT SPICY':'GET FAUXBULOUS';if(chip)chip.textContent=mode==='horror'?'HORROR MODE · dark, cinematic, practical or psychological':mode==='spicy'?'SPICY MODE · adult, sensual, luxe, non-explicit':'NORMAL MODE · glam, editorial, cinematic, creative';const h=$('#hBtn');if(h)h.closest('.suiteBtn')?.classList.toggle('smartHidden',mode!=='horror'&&false);const title=$('.smartHead .cardTitle',sections.details);if(title)title.textContent=mode==='horror'?'HORROR DETAILS':mode==='spicy'?'SPICY DETAILS + CREATOR TOOLS':'CREATOR TOOLS';ensureSpicyDetails()}
function ensureSpicyDetails(){if(!sections.details)return;let box=$('#spicySmartDetails');if(mode==='spicy'){if(!box){box=document.createElement('div');box.id='spicySmartDetails';box.className='modeNotice';box.innerHTML=`<b>Heat level</b><select id="spicyHeat" class="smartInput" style="margin-top:7px"><option>Soft tease</option><option>Flirty</option><option selected>Hot editorial</option><option>Maximum non-explicit heat</option></select>`;$('.smartBody',sections.details).prepend(box);$('#spicyHeat').value=localStorage.getItem(HEAT_KEY)||'Hot editorial';$('#spicyHeat').onchange=e=>localStorage.setItem(HEAT_KEY,e.target.value)}}else box?.remove()}
async function pickValue(key,value){const b=$(`[data-pick="${key}"]`);if(!b)return;b.click();await wait(0);let item=$$('.pickItem',$('#pickerList')).find(x=>x.textContent.trim()===value);if(!item){item=$$('.pickItem',$('#pickerList')).find(x=>x.textContent.trim()==='Custom…');if(item){item.click();await wait(0);$('#customInput').value=value}else return $('#pickerClose')?.click()}else item.click();await wait(0);$('#pickerConfirm')?.click();await wait(0)}
async function clearPick(key){const b=$(`[data-pick="${key}"]`);if(!b)return;b.click();await wait(0);const item=$$('.pickItem',$('#pickerList')).find(x=>/Blank \/ clear choice/i.test(x.textContent));if(item){item.click();$('#pickerConfirm')?.click();await wait(0)}else $('#pickerClose')?.click()}
const LOOKS={normal:[['Confident','Voluminous waves','Soft glam','Power stance'],['Smirk','Sleek straight','90s supermodel glam','Over-shoulder look'],['Dreamy','Hollywood curls','Vogue editorial glam','Seated elegance'],['Sassy','High ponytail','Full glam','Hand on hip']],horror:[['Intense stare','Tousled texture','Goth glam','Direct stare'],['Unimpressed','Slicked-back','Smoky eye','Low-to-the-ground editorial pose'],['Mysterious','Updo couture','Vogue editorial glam','Over-shoulder look'],['Side-eye','Messy bun','Punk glam','Looking away']],spicy:[['Flirty','Voluminous waves','Full glam','Confident hip-shift with direct eye contact'],['Smirk','Hollywood curls','90s supermodel glam','Seated sideways with one knee raised'],['Confident','Sleek straight','Smoky eye','Leaning back against a wall with sultry expression'],['Playful','High ponytail','Y2K glossy glam','Standing with crossed legs and hand at waist']]};
const SCENES={normal:[['Outdoor','Rooftop skyline','Blue hour','Clear skies','Luxury editorial'],['Indoor','Art gallery opening','Late evening','Clear skies','High-fashion serious'],['Outdoor','Rainy street','Night','Light rain','Cinematic action'],['Indoor','Luxury studio set','Afternoon','Clear skies','Glamorous']],horror:[['Indoor','Abandoned motel corridor','Midnight','Fog','Mysterious'],['Indoor','Liminal fluorescent hallway','Night','Clear skies','Noir'],['Outdoor','Foggy forest clearing','Moonlit night','Fog','Horror-lite stylish'],['Indoor','Wrong-feeling suburban living room','Late evening','Thunderstorm','Mysterious']],spicy:[['Indoor','Velvet lounge set','Late evening','Clear skies','Sultry high-fashion'],['Indoor','Dark luxury hotel suite','Candlelit evening','Clear skies','Dark feminine glamour'],['Outdoor','Private rooftop lounge at night','Blue hour','Clear skies','After-dark magazine editorial'],['Indoor','Luxury dressing room','Night','Clear skies','Confident bombshell editorial']]};
const CAMERAS={normal:[['Full-body fashion','Cinematic 35mm'],['Three-quarter angle','85mm portrait'],['Low angle hero shot','Cinematic 50mm'],['High angle editorial','Wide 24mm fashion']],horror:[['Doorway frame','Cinematic 35mm'],['Dutch tilt','Wide 24mm fashion'],['Overhead','Cinematic 50mm'],['Foreground blur framing','85mm portrait']],spicy:[['Three-quarter angle','85mm portrait'],['Low angle hero shot','Cinematic 50mm'],['Tight beauty close-up','85mm portrait'],['Full-body fashion','Cinematic 35mm']]};
const LIGHTS={normal:['Soft beauty light','Cinematic side light','Blue hour cool light','Hard fashion light'],horror:['Moody shadow light','Cool daylight','Film noir contrast','Top-down spotlight'],spicy:['Cinematic side light','Warm tungsten','Soft beauty light','Backlight halo']};
async function surpriseSection(id){if(locks[id])return;if(id==='who'){const count=rand([1,1,1,2,2,3]);const pills=$$('#countPills .pill');pills[count-1]?.click();await wait(0);rand($$('#genderPills .pill'))?.click();if(count>1)await pickValue('interaction',rand(['Laughing together','Back-to-back pose','Fashion duo vibe','Dramatic cinematic embrace']));}
  if(id==='look'){const [ex,hair,mk,pose]=rand(LOOKS[mode]||LOOKS.normal);await pickValue('expression',ex);await pickValue('hairStyle',hair);await pickValue('hairTexture',rand(['Soft curls','Silky','Sleek gloss','High volume']));await pickValue('hairColor',rand(['Black','Chocolate','Burgundy','Hot pink','Violet','Silver','Gold']));const mt=$('#mkToggle');if(mt?.getAttribute('aria-pressed')!=='true')mt.click();await pickValue('makeup',mk);const lt=$('#lashToggle');if(lt?.getAttribute('aria-pressed')!=='true')lt.click();await pickValue('pose',pose);await pickValue('nailsStyle',rand(['Almond','Coffin','Chrome','Glossy']));await pickValue('nailsColor',rand(['Black','Cherry red','Hot pink','Violet','Silver','Gold']));}
  if(id==='wardrobe'){const path=rand(mode==='spicy'?['separates','dress','separates','dress']:mode==='horror'?['separates','dress','costume','separates']:['separates','dress','separates','onesie']);if(path==='separates'){await pickValue('tops',rand(mode==='spicy'?['Structured corset top','Satin cowl-neck top','Off-shoulder fitted top']:['Blazer','Leather top','Silk blouse','Graphic tee']));await pickValue('bottoms',rand(['Leather pants','Tailored trousers','Wide-leg jeans','Mini skirt']));}if(path==='dress')await pickValue('dresses',rand(mode==='spicy'?['Velvet dress','Satin dress','Bodycon dress','Corset dress']:mode==='horror'?['Velvet dress','Leather dress','Sculptural editorial dress','Lace dress']:['Couture gown','Blazer dress','Satin dress','Sculptural editorial dress']));if(path==='onesie')await pickValue('onesies',rand(['Cozy pajama onesie','Galaxy onesie','Skeleton onesie']));if(path==='costume')await pickValue('costumes',rand(['Gothic vampire','Witch look','Monster couture','Skeleton glam']));await pickValue('shoes',rand(['Ankle boots','Platform heels','Combat boots','Designer pumps']));await pickValue('accessories',rand(['Sunglasses','Statement belt','Leather gloves','Designer handbag']));await pickValue('jewelry',rand(['Gold hoops','Silver hoops','Rings stack','Statement ring']));}
  if(id==='scene'){const [io,e,t,w,m]=rand(SCENES[mode]||SCENES.normal);await pickValue('sceneIO',io);await pickValue('environment',e);await pickValue('timeOfDay',t);await pickValue('weather',w);await pickValue('mood',m);}
  if(id==='camera'){const [a,l]=rand(CAMERAS[mode]||CAMERAS.normal);await pickValue('cameraAngle',a);await pickValue('lens',l);}
  if(id==='lighting')await pickValue('lighting',rand(LIGHTS[mode]||LIGHTS.normal));
  if(id==='details'){if(mode==='horror'){const h=$('#hBtn');h?.click();await wait(0);const types=['practical','psychological','supernatural','creature','slasher','liminal','beautiful'];$('#hType').value=rand(types);$('#hInt').value=rand([60,70,80,90]);$('#hGore').value=$('#hType').value==='psychological'||$('#hType').value==='liminal'?'none':rand(['light','moderate']);$('#hFx').value=rand(['Detailed','Extreme cinematic']);$('#hSeed').value=rand(['Every mirror reflects a different expression.','The hallway becomes longer every time she looks away.','A family photograph changes while she is holding it.','Something in the room is copying her posture one second late.']);$('#hApply')?.click()}else if(mode==='spicy'){ensureSpicyDetails();$('#spicyHeat').value=rand(['Soft tease','Flirty','Hot editorial','Maximum non-explicit heat']);localStorage.setItem(HEAT_KEY,$('#spicyHeat').value)}else{$('#str').value=rand([2,3,4]);$('#str').dispatchEvent(new Event('input',{bubbles:true}))}}
  if(id==='inspo'){const checks=$$('[data-inspo]',sections.inspo);checks.forEach(x=>x.checked=false);rand([[0,5,6,7],[1,4,7],[0,3,4,5],[2,3,6,9],[0,1,6,8]]).forEach(i=>{if(checks[i])checks[i].checked=true});saveInspoMeta()}
  if(id==='extras'){const scrap=$('#scrapToggle');if(mode==='horror'||mode==='spicy'){if(scrap?.getAttribute('aria-pressed')==='true')scrap.click()}else{if(scrap?.getAttribute('aria-pressed')!=='true')scrap.click();await pickValue('scrapStyle',rand(['Luxury fashion scrapbook','Minimal clean scrapbook','Magazine cutout collage']));await pickValue('scrapElements',rand(['Polaroid frames','Film strips','Foil accents']))}}
  await wait(10);updateContradictions();updateSummaries();flashSection(id)}
async function surpriseEverything(){const order=['who','look','wardrobe','scene','camera','lighting','details','inspo','extras'];const b=$('#surpriseAll');if(b){b.disabled=true;b.textContent='BUILDING…'}for(const id of order)if(!locks[id]&&sections[id])await surpriseSection(id);if(b){b.disabled=false;b.textContent='🎲 SURPRISE EVERYTHING'}}
async function clearSection(id){if(locks[id])return;const map={look:['expression','pose','hairStyle','hairColor','hairTexture','makeup','nailsStyle','nailsColor'],wardrobe:['tops','topsColor','bottoms','bottomsColor','dresses','dressesColor','onesies','onesiesColor','costumes','costumesColor','shoes','shoesColor','accessories','jewelry'],scene:['sceneIO','environment','timeOfDay','weather','mood'],camera:['cameraAngle','lens'],lighting:['lighting']};if(map[id])for(const k of map[id])await clearPick(k);if(id==='look'){if($('#mkToggle')?.getAttribute('aria-pressed')==='true')$('#mkToggle').click();if($('#lashToggle')?.getAttribute('aria-pressed')==='true')$('#lashToggle').click();if($('#pierToggle')?.getAttribute('aria-pressed')==='true')$('#pierToggle').click();if($('#tatToggle')?.getAttribute('aria-pressed')==='true')$('#tatToggle').click()}if(id==='who'){const p=$$('#countPills .pill');p[0]?.click();const f=$$('#genderPills .pill');f[0]?.click()}if(id==='details'&&mode==='horror'){$('#hBtn')?.click();await wait(0);$('#hOff')?.click()}if(id==='inspo'){saveInspo({images:[],aspects:[]});renderInspo()}if(id==='extras'){if($('#namesOnImg')?.getAttribute('aria-pressed')==='true')$('#namesOnImg').click();if($('#dateOnImg')?.getAttribute('aria-pressed')==='true')$('#dateOnImg').click()}updateContradictions();updateSummaries()}
function updateContradictions(){const top=selected('tops'),bot=selected('bottoms'),dress=selected('dresses'),one=selected('onesies'),cost=selected('costumes');const show=(k,on)=>fieldForPick(k)?.classList.toggle('smartHidden',!on);if(dress){show('tops',false);show('bottoms',false);show('onesies',false);show('costumes',false);show('dresses',true)}else if(one){show('tops',false);show('bottoms',false);show('dresses',false);show('costumes',false);show('onesies',true)}else if(cost){show('tops',false);show('bottoms',false);show('dresses',false);show('onesies',false);show('costumes',true)}else if(top||bot){show('tops',true);show('bottoms',true);show('dresses',false);show('onesies',false);show('costumes',false)}else ['tops','bottoms','dresses','onesies','costumes'].forEach(k=>show(k,true));const inter=fieldForPick('interaction');const s=getCoreState();if(inter)inter.classList.toggle('smartHidden',(+s.peopleCount||1)===1)}
function updateSummaries(){const vals={who:(()=>{const s=getCoreState();return `${s.peopleCount||1} person${(+s.peopleCount||1)>1?'s':''}`})(),look:[selected('expression'),selected('hairStyle'),selected('pose')].filter(Boolean).join(' · '),wardrobe:[selected('tops'),selected('bottoms'),selected('dresses'),selected('onesies'),selected('costumes')].filter(Boolean).join(' · '),scene:[selected('environment'),selected('timeOfDay')].filter(Boolean).join(' · '),camera:[selected('cameraAngle'),selected('lens')].filter(Boolean).join(' · '),lighting:selected('lighting'),details:mode==='horror'?'Horror controls':mode==='spicy'?(localStorage.getItem(HEAT_KEY)||'Hot editorial'):'Creator controls',inspo:(()=>{const m=getInspo();return m.images.length?`${m.images.length} image${m.images.length>1?'s':''} · ${m.aspects.slice(0,2).join(', ')}`:'No inspo'})(),extras:$('#sigOnImg')?.getAttribute('aria-pressed')==='true'?'Signature on':'Extras'};Object.entries(vals).forEach(([id,v])=>{const s=$('.smartSummary',sections[id]);if(s)s.textContent=v||'Not set'})}
function flashSection(id){const c=sections[id];if(!c)return;c.animate([{boxShadow:'0 0 0 transparent'},{boxShadow:'0 0 32px var(--modeA)'},{boxShadow:'0 0 0 transparent'}],{duration:550})}
function enhancePrompt(){const ta=$('#promptText');if(!ta||!ta.value)return;let t=ta.value;const hash=t.match(/\n\n(#rebeccalynndeulen[^\n]*)\s*$/i);let tags='';if(hash){tags=hash[1];t=t.slice(0,hash.index).trimEnd()}if(mode==='horror'&&!/HORROR MODE: ON/i.test(t)){const insert='\n\nHORROR MODE: ON. Build one coherent cinematic horror concept. Favor physical plausibility, practical effects when applicable, unsettling atmosphere, believable anatomy and a deliberate story beat. Avoid random horror clutter or contradictory visual ideas.';const ix=t.indexOf('\n\nIMAGE LAYOUT:');t=ix>-1?t.slice(0,ix)+insert+t.slice(ix):insert+'\n'+t}if(mode==='spicy'){const heat=localStorage.getItem(HEAT_KEY)||'Hot editorial';t=t.replace('SPICY MODE: ON.','SPICY MODE: ON. Heat direction: '+heat+'.')}
  const m=getInspo();if(m.images.length&&m.aspects.length){const sec=`\n\nCREATIVE DIRECTION REFERENCES:\n- Use the separately uploaded inspiration image${m.images.length>1?'s':''} only for: ${m.aspects.join(', ')}.\n- Do not use inspiration images as identity references. Identity must come only from the designated person reference photo(s).\n- Translate the references into one coherent original image rather than copying unrelated details.`;const ix=t.indexOf('\n\nFINAL REALISM RULES:');t=ix>-1?t.slice(0,ix)+sec+t.slice(ix):t+sec}
  const sceneStart=t.indexOf('\n\nSCENE & STYLE:'),peopleStart=t.indexOf('\n\nPEOPLE:');if(sceneStart>-1&&peopleStart>sceneStart){const next=t.indexOf('\n\n',peopleStart+10);if(next>-1){const sceneBlock=t.slice(sceneStart,peopleStart);const peopleBlock=t.slice(peopleStart,next);t=t.slice(0,sceneStart)+peopleBlock+sceneBlock+t.slice(next)}}
  ta.value=(t.trimEnd()+(tags?'\n\n'+tags:'')).trim()}
function loadingForMode(){if(mode!=='horror')return;const p=$('#promptModal');const l=document.createElement('div');l.className='modeLoading';l.innerHTML='<div>Summoning the darker side…<small>Building something that actually makes sense.</small></div>';document.body.appendChild(l);setTimeout(()=>{l.remove();p?.classList.remove('hidden')},700);setTimeout(()=>p?.classList.add('hidden'),0)}
function observe(){const target=$('#content');if(!target)return;new MutationObserver(()=>{updateContradictions();updateSummaries();updateMode()}).observe(target,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['aria-pressed']})}
window.addEventListener('DOMContentLoaded',()=>{setTimeout(()=>{restructure();observe();document.addEventListener('click',e=>{if(e.target.closest('[data-pick],.toggleBtn,.pill,.suiteAction'))setTimeout(()=>{updateContradictions();updateSummaries()},5)});const go=$('#goBtn');if(go){go.addEventListener('click',loadingForMode,true);go.addEventListener('click',()=>setTimeout(enhancePrompt,12))}},40)});
})();