/* AI-FAUXBULOUS visual layer v32 */
(()=>{'use strict';
const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)];
const CREATOR='./assets/rebecca-creator-v31.jpg?v=32';
const WIDE='./assets/rebecca-wide-v31.jpg?v=32';
const CLOSE_KEY='faux-creator-card-closed-v32';
const heroHTML='<div><div class="eyebrow">FAUX STUDIO</div><div class="heroTitle">Build something <span>fauxbulous.</span></div><div class="heroSub">Custom image prompts with identity-safe styling, camera direction, story, and glam.</div></div>';
const css=`
.hero{display:block!important;visibility:visible!important;opacity:1!important;min-height:0!important;height:auto!important;padding:18px 20px!important;background:linear-gradient(135deg,#1d1324,#151021)!important;color:#fff!important}.hero>*{display:block!important;visibility:visible!important;opacity:1!important}.hero .spicyBtn{display:none!important}.heroTitle{display:block!important;color:#fff!important}.heroTitle span{color:#ff67d2!important}.heroSub,.eyebrow{display:block!important}
.creatorCard,.fauxCreatorCard,#fauxCreatorCard,[data-faux-creator],#creatorV31{display:none!important}
#creatorV32{display:grid!important;grid-template-columns:104px minmax(0,1fr);gap:15px;align-items:center;position:relative;margin:14px 0 18px;padding:14px 58px 14px 14px;border:1px solid #ffffff22;border-radius:24px;background:linear-gradient(135deg,#211524,#15101d);overflow:hidden;color:#fff}
#creatorV32 img{width:104px;height:104px;display:block;object-fit:cover;object-position:50% 30%;border-radius:22px;border:1px solid #ffffff33}#creatorV32 .copy{min-width:0}#creatorV32 .ey{font-size:9px;letter-spacing:2.4px;color:#ffffff8c;font-weight:900;margin-bottom:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#creatorV32 .nm{font-size:17px;font-weight:950;line-height:1.08;overflow-wrap:anywhere}#creatorV32 .sb{font-size:10.5px;line-height:1.35;color:#ffffffb8;margin-top:7px}#creatorV32 .x{position:absolute;right:12px;top:12px;width:38px;height:38px;border-radius:50%;border:1px solid #ffffff30;background:#09060c;color:#fff;font-size:20px;font-weight:900}
#founderMini,#founderV31{display:none!important}.actionCard{min-height:0!important;height:auto!important;padding:14px!important;overflow:visible!important}.actionCard>*{max-height:none!important}#founderV32{position:relative;margin:0 0 14px;border-radius:20px;overflow:hidden;background:#050307;border:1px solid #ffffff20}#founderV32 img{display:block;width:100%;height:auto!important;aspect-ratio:auto!important;object-fit:contain!important;background:#050307}#founderV32 .tag{position:absolute;right:12px;bottom:10px;padding:6px 10px;border-radius:999px;background:#08060bcc;border:1px solid #ffffff25;color:#fff;font-size:8px;font-weight:900;letter-spacing:1.2px}
@media(max-width:520px){#creatorV32{grid-template-columns:88px minmax(0,1fr);gap:12px;padding:12px 52px 12px 12px}#creatorV32 img{width:88px;height:88px}#creatorV32 .nm{font-size:15px}#creatorV32 .sb{font-size:9.5px}.heroTitle{font-size:26px!important}.heroSub{font-size:13px!important}}
`;
function style(){if($('#visualV32Style'))return;const s=document.createElement('style');s.id='visualV32Style';s.textContent=css;document.head.appendChild(s)}
function restoreHero(){const h=$('.hero');if(!h)return;const title=$('.heroTitle',h),sub=$('.heroSub',h);if(!title||!sub||!title.textContent.trim())h.innerHTML=heroHTML;}
function purgeLegacy(){ $$('.creatorCard,.fauxCreatorCard,#fauxCreatorCard,[data-faux-creator],#creatorV31').forEach(e=>e.remove()); $('#founderMini')?.remove(); $('#founderV31')?.remove(); }
function creator(){if(localStorage.getItem(CLOSE_KEY)==='1')return;if($('#creatorV32'))return;const deck=$('#fauxModeDeck'),hero=$('.hero');if(!deck&&!hero)return;const c=document.createElement('section');c.id='creatorV32';c.innerHTML='<img src="'+CREATOR+'" alt="Rebecca Lynn"><div class="copy"><div class="ey">THE HUMAN BEHIND THE FAUX</div><div class="nm">Brought to you by Rebecca Lynn / Fauxbulous</div><div class="sb">Better AI image prompts without needing a photography degree or seventeen browser tabs.</div></div><button class="x" type="button" aria-label="Close creator card">×</button>';c.querySelector('.x').onclick=()=>{localStorage.setItem(CLOSE_KEY,'1');c.remove()};(deck||hero).after(c);}
function founder(){const action=$('.actionCard');if(!action)return;let f=$('#founderV32');if(!f){f=document.createElement('div');f.id='founderV32';f.innerHTML='<img src="'+WIDE+'" alt="Rebecca Lynn reclining"><div class="tag">REBECCA LYNN · FAUXBULOUS</div>';action.prepend(f);}action.style.setProperty('min-height','0','important');action.style.setProperty('height','auto','important');}
function enforce(){style();purgeLegacy();restoreHero();creator();founder();}
function boot(){enforce();setTimeout(enforce,250);setTimeout(enforce,900);const root=$('#app')||document.body;new MutationObserver(()=>{clearTimeout(window.__fauxVisual32T);window.__fauxVisual32T=setTimeout(enforce,40)}).observe(root,{childList:true,subtree:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();